### ISSUE TITLE
rpi - error after script auto install

### ISSUE THREAD

**Issue by drmarian** [kryops/01v96-remote#14]
/home/pi/01v96-remote/node_modules/uws/uws.js:3
const http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/01v96-remote/server/controllers/socket.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by kryops** [comment]
Which version of node.js are you running? The  `uws` module requires at least version 4.
For older versions, you might be able to run it with the `--harmony` flag to enable additional features that were still flagged as experimental.
Alternatively, you can use an older version of this project, e.g. https://github.com/kryops/01v96-remote/tree/491c455a18d4c61623d87e05e6fdad68620ade33

**Comment by Fruudcake** [comment]
I'm having the exact same issue. I tried installing it but changing the uws dependency to 0.14.1 instead of 0.12.0 in package.json breaks it. 0.12.0 is not available anymore. 

```
npm ERR! notarget No compatible version found: uws@'>=0.13.0-0 <0.14.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.14.1"]
```

**Comment by kryops** [comment]
I just noticed that the install scripts still point to the old NodeJS v0.10.24, sorry for that! I changed that to the current LTS release v6.10.2. However, I don't have a Raspberry Pi to test it at the moment, so I cannot guarantee that it works as expected.

**Comment by Fruudcake** [comment]
I get this now, I think it's because forever has moved to the /opt/node/bin folder?

```
pi@raspberrypi:~ $ sudo /etc/init.d/forever-01v96-remote start
starting Forever NodeJS: /home/pi/01v96-remote/server.js serialport
sudo: /usr/bin/forever: command not found
```

**Comment by kryops** [comment]
@Fruudcake does it work if you replace `EXE=/usr/bin/forever` with `EXE=/opt/node/bin/forever` in `/etc/init.d/forever-01v96-remote`?

**Comment by Fruudcake** [comment]
Yes! It's fixed now. At first it wasn't because there was another instance running, but after rebooting and a restart it works fine! Thanks for fixing it so fast. :) I'll test to see if it's stable.

**Comment by kryops** [comment]
Thanks for helping me repair it! It's a bit hard without having the hardware to test it - maybe I should investigate simulating a Raspberry Pi in a virtual machine :flushed: 
I changed the path to `forever` in the docs and install scripts.

**Comment by Fruudcake** [comment]
You're welcome and thank you for making this great app. Also you need to change the serialport parameter in the setup-usb.sh script to midi I think? I've changed that on my setup to get it to work.

Do you have any plans to integrate the channelstrip part in this app? I love your clean layout.

**Comment by kryops** [comment]
Fixed, thanks!

The app was designed to have a quite limited functionality because the original Raspberry Pi was really slow and just displaying the faders in real-time would usually challenge it. Now with faster models and newer software it might actually be possible.
However, I don't have a 01v96 available at the moment either (I moved abroad for a year), so looking into extending the features will have to wait until I'm back :disappointed:

You can always open issues for features you would like to be added, maybe I can come back to it next year :wink:

**Comment by Fruudcake** [comment]
Metering, levels en mute is fine for now! Just wondering if you had any plans.
Is that also the reason why fader resolution has to be set to low, because of the slow original Pi?

Thanks again!

**Comment by kryops** [comment]
I'm actually not sure any more. Maybe there was just no need for the high resolution, the low one still has 256 fader levels 😅

**Comment by Fruudcake** [comment]
There is no need for it indeed, it's fine the way it is. ;)
Is it easy to add aux 5-8? There is not much room on the interface as a tab, but maybe as dropdown or something? That would make it complete as far as levels/metering/mute goes. :D

**Comment by kryops** [comment]
That was another limit I introduced for performance reasons :smile:
In the long term it's probably best to add a configuration variable for the number of aux entries you need. Most of the times I used the app for smaller setups with 1 or 2 aux ways, so displaying all of them would have been a bit of an overkill. I will open an issue to investigate the best solution.

If you need all 8 auxes or want to try and play around with the confiugration a bit, you can add them yourself quite easily like this:
https://github.com/kryops/01v96-remote/commit/3532d686838608ab50efc623a597b4a30ecb2b52
