### ISSUE TITLE
RPi setup-usb.sh script error

### ISSUE THREAD

**Issue by Fruudcake** [kryops/01v96-remote#15]
Hello,

After running the setup-usb.sh script I get this error:

```
npm ERR! notarget No compatible version found: uws@'>=0.13.0-0 <0.14.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.14.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/01v96-remote
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/01v96-remote/npm-debug.log
npm ERR! not ok code 0
```
 
EDIT: I've tried to fix the dependencies but it doesn't seem to want to run on newer versions.

```
[events] Fired: ready
[static] Web server started at port 1337
[socket] WebSocket server started at port 1338
[mixer] Using standard MIDI controller
[mixer_midi] MIDI input port 1 / 01V96 20:0
[mixer_midi] MIDI output port 1 / 01V96 20:0
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Array.init (/home/pi/01v96-remote/server/controllers/static.js:21:8)
    at Object.fire (/home/pi/01v96-remote/server/modules/events.js:71:28)
    at Object.<anonymous> (/home/pi/01v96-remote/server.js:35:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
error: Forever detected script exited with code: 1
```

**Comment by kryops** [comment]
Thanks for your report! I upgraded uws to 0.14.1, all prior versions seem to have been unpublished from npm: https://github.com/uWebSockets/uWebSockets/issues/551
